//! Where the management endpoint is, according to the server itself.
//!
//! Every value here is read from `server.properties` at the point of use, for
//! the reason the whole tree reads that file rather than copying it: the JVM
//! rewrites it, and a mirror in mc's own config could only go stale. The
//! secret in particular is generated by the server when the property is left
//! empty, so a cached copy would be wrong on exactly the first start that
//! matters.

use mc_common::error::{Error, Result};
use mc_common::properties::Properties;

/// The property that switches the protocol on. Everything else is optional.
pub const ENABLED: &str = "management-server-enabled";
pub const HOST: &str = "management-server-host";
pub const PORT: &str = "management-server-port";
pub const SECRET: &str = "management-server-secret";
pub const TLS: &str = "management-server-tls-enabled";



/// A resolved endpoint: where to connect, and what to authenticate with.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Endpoint {
    pub url: String,
    pub secret: String,
    pub host: String,
    pub port: u16,
}

impl Endpoint {
    /// True when the endpoint is one this machine reaches without a network.
    ///
    /// Not a refusal — unlike RCON, this protocol has a bearer secret and can
    /// be fronted by a TLS-terminating proxy, so a non-loopback endpoint is a
    /// legitimate deployment rather than a mistake. Callers use this to decide
    /// what to *warn* about.
    pub fn is_loopback(&self) -> bool {
        matches!(
            self.host.as_str(),
            "localhost" | "127.0.0.1" | "::1" | "[::1]"
        )
    }
}

/// Read the endpoint out of `server.properties`.
///
/// `None` when the protocol is switched off, which is not an error: it is the
/// stock state of every server, and of every server older than 1.21.9.
pub fn resolve(props: &Properties) -> Option<Endpoint> {
    if props.get(ENABLED) != Some("true") {
        return None;
    }

    let host = props.get(HOST).unwrap_or("localhost").trim().to_string();
    let host = if host.is_empty() {
        "localhost".to_string()
    } else {
        host
    };

    // Port 0 means "the server picked one at random", which is useless to a
    // client: there is nowhere to look it up. mc pins a port at provision time
    // precisely so this cannot happen, and a 0 here means somebody edited the
    // file back.
    let port: u16 = props.get(PORT).and_then(|p| p.trim().parse().ok())?;
    if port == 0 {
        return None;
    }

    let secret = props.get(SECRET).unwrap_or_default().trim().to_string();
    // TLS defaults to ON in the protocol, so an absent key means wss://.
    let scheme = if props.get(TLS) == Some("false") {
        "ws"
    } else {
        "wss"
    };

    // An IPv6 literal has to be bracketed in a URL authority, and the property
    // holds it bare.
    let authority = if host.contains(':') && !host.starts_with('[') {
        format!("[{host}]")
    } else {
        host.clone()
    };

    Some(Endpoint {
        url: format!("{scheme}://{authority}:{port}"),
        secret,
        host,
        port,
    })
}

/// The endpoint, or an error that says which of the several possible reasons
/// applies.
///
/// Split from [`resolve`] because the console probe wants a silent `None` and
/// `mc mgmt` wants to tell an operator what to fix.
pub fn require(props: &Properties) -> Result<Endpoint> {
    let endpoint = resolve(props).ok_or_else(|| {
        Error::config(
            "The management protocol is not enabled on this server.\n       \
             It needs Minecraft 1.21.9 or newer. Enable it with: mc mgmt enable",
        )
    })?;

    if endpoint.secret.is_empty() {
        return Err(Error::config(format!(
            "{SECRET} is empty in server.properties — nothing can authenticate.\n       \
             Provision one with: mc mgmt enable"
        )));
    }
    Ok(endpoint)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn props(pairs: &[(&str, &str)]) -> Properties {
        let mut props = Properties::default();
        for (key, value) in pairs {
            props.set(key, value);
        }
        props
    }

    #[test]
    fn a_server_with_the_protocol_switched_off_has_no_endpoint() {
        // The stock state, and the state of every server older than 1.21.9.
        // Not an error: it is what the console probe expects to find most of
        // the time.
        assert!(resolve(&props(&[])).is_none());
        assert!(resolve(&props(&[(ENABLED, "false"), (PORT, "25585")])).is_none());
    }

    #[test]
    fn a_random_port_is_no_port_at_all() {
        // 0 tells the server to pick one, and a client has nowhere to read the
        // choice back from. mc pins the port when it provisions.
        let p = props(&[(ENABLED, "true"), (PORT, "0"), (SECRET, "s")]);
        assert!(resolve(&p).is_none());
    }

    #[test]
    fn tls_is_assumed_on_unless_the_server_says_otherwise() {
        // The protocol's own default. Getting this backwards would send a
        // plaintext handshake at a TLS listener and report a parse error.
        let p = props(&[(ENABLED, "true"), (PORT, "25585"), (SECRET, "s")]);
        assert_eq!(resolve(&p).unwrap().url, "wss://localhost:25585");

        let p = props(&[
            (ENABLED, "true"),
            (PORT, "25585"),
            (SECRET, "s"),
            (TLS, "false"),
        ]);
        assert_eq!(resolve(&p).unwrap().url, "ws://localhost:25585");
    }

    #[test]
    fn an_ipv6_host_is_bracketed_for_the_url() {
        let p = props(&[
            (ENABLED, "true"),
            (HOST, "::1"),
            (PORT, "25585"),
            (SECRET, "s"),
            (TLS, "false"),
        ]);
        let endpoint = resolve(&p).unwrap();
        assert_eq!(endpoint.url, "ws://[::1]:25585");
        assert!(endpoint.is_loopback());
    }

    #[test]
    fn a_non_loopback_endpoint_is_reported_not_refused() {
        // Unlike RCON. This protocol authenticates with a bearer secret and is
        // designed to sit behind a TLS-terminating proxy, so binding elsewhere
        // is a deployment choice rather than the mistake it is for RCON.
        let p = props(&[
            (ENABLED, "true"),
            (HOST, "10.0.0.5"),
            (PORT, "25585"),
            (SECRET, "s"),
        ]);
        let endpoint = resolve(&p).unwrap();
        assert!(!endpoint.is_loopback());
        assert_eq!(endpoint.url, "wss://10.0.0.5:25585");
    }

    #[test]
    fn an_empty_secret_is_named_as_the_problem() {
        let p = props(&[(ENABLED, "true"), (PORT, "25585")]);
        let error = require(&p).expect_err("no secret");
        assert!(error.to_string().contains(SECRET), "{error}");
    }

    #[test]
    fn a_disabled_server_says_which_version_it_would_need() {
        let error = require(&props(&[])).expect_err("disabled");
        assert!(error.to_string().contains("1.21.9"), "{error}");
    }
}
