apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bulmer-apt
  namespace: bulmer-apt
spec:
  ingressClassName: nginx
  rules:
    - host: apt.bulmer.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bulmer-apt
                port:
                  number: 80
